sudo: required

language: python
python: 3.4

before_install:
    # all these shenanigans are because docker-py wants docker remote api 1.21
    # but travis has 1.20
    # and downgrading causes some SSL issue locally on OSX
    - sudo apt-get -qq update -y
    - sudo apt-get install apt-transport-https ca-certificates -y
    - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - sudo apt-get install -y linux-image-extra-virtual
    - sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-precise main > /etc/apt/sources.list.d/docker.list"
    - sudo apt-get -qq update -y
    - sudo apt-get install docker-engine=1.9.1-0~precise -y
    - sudo gpasswd -a ${USER} docker
    - sudo service docker restart
    - sudo -E docker pull redis

env:
  - TOX_ENV=py34
install:
  - pip install tox
script:
    # weird sudo thing so that the travis user can use docker installed by apt
    - sudo -E "PATH=$PATH" ./the_build.sh
